version: '3.9'
services:
  postgres:
    image: postgres:15  # ใช้ image PostgreSQL version 15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres_user          # ชื่อผู้ใช้
      POSTGRES_PASSWORD: postgres_password  # รหัสผ่าน
      POSTGRES_DB: my_db                    # ชื่อฐานข้อมูลเริ่มต้น
    ports:
      - "5432:5432"  # Map พอร์ตของ PostgreSQL (ใน container) กับ host
    volumes:
      - ./ref:/data  # แชร์โฟลเดอร์ ./ref ไปยัง /data ใน container
      - postgres_data:/var/lib/postgresql/data  # เก็บข้อมูลถาวร

  pgadmin:
    image: dpage/pgadmin4  # ใช้ image pgAdmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # email login pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin1234       # password login pgAdmin
    ports:
      - "5050:80"  # Map พอร์ต 5050 (host) กับพอร์ต 80 (pgAdmin container)
    depends_on:
      - postgres

volumes:
  postgres_data:  # Volume สำหรับเก็บข้อมูล PostgreSQL ถาวร
